version: '3.8'

services:
  zin-ssh-server:
    build: .
    image: zin-private-ssh:latest
    container_name: zin_ssh_container
    ports:
      - "8080:8080"  # منفذ Websocket (الذي يوضع في الهوست الخاص بالتطبيق)
      - "2222:22"    # منفذ SSH العادي (اختياري)
    restart: always
    environment:
      - USER_NAME=zin_user
      - USER_PASS=ZinCloud@2024
